--
-- Flyway V1 baseline: the complete schema as it exists in the live
-- duedilligence_db database (PostgreSQL 18.6), regenerated 2026-09-28
-- via pg_dump --schema-only. Baseline-on-migrate marks existing
-- databases as pre-V1 (this file is NOT applied there); on a FRESH
-- database Flyway applies it to create the exact schema. Hibernate
-- ddl-auto=validate then only validates against it.
--
-- Data (admin user, 50-property seed) is loaded separately via
-- spring.sql.init.data-locations AFTER schema creation.
--

--
-- PostgreSQL database dump
--


-- Dumped from database version 18.6 (Ubuntu 18.6-1.pgdg24.04+2)
-- Dumped by pg_dump version 18.6 (Ubuntu 18.6-1.pgdg24.04+2)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: activity_logs; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.activity_logs (
    activity_log_id bigint NOT NULL,
    action character varying(100) NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    entity_id bigint,
    entity_type character varying(50),
    user_id bigint NOT NULL
);


--
-- Name: activity_logs_activity_log_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.activity_logs ALTER COLUMN activity_log_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.activity_logs_activity_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: aggregation_runs; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.aggregation_runs (
    aggregation_run_id bigint NOT NULL,
    completed_at timestamp(6) without time zone,
    property_id bigint NOT NULL,
    requested_address character varying(500) NOT NULL,
    started_at timestamp(6) without time zone NOT NULL,
    status character varying(30) NOT NULL
);


--
-- Name: aggregation_runs_aggregation_run_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.aggregation_runs ALTER COLUMN aggregation_run_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.aggregation_runs_aggregation_run_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: api_logs; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.api_logs (
    api_log_id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    endpoint character varying(255) NOT NULL,
    error_message character varying(500),
    request_time timestamp(6) without time zone NOT NULL,
    response_time timestamp(6) without time zone,
    service_name character varying(100) NOT NULL,
    status_code integer,
    success boolean
);


--
-- Name: api_logs_api_log_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.api_logs ALTER COLUMN api_log_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.api_logs_api_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: building_permit_details; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.building_permit_details (
    permit_id bigint NOT NULL,
    completion_date date,
    description character varying(500),
    external_record_id character varying(100),
    issue_date date,
    permit_number character varying(50) NOT NULL,
    permit_status character varying(30),
    permit_type character varying(50),
    property_id bigint NOT NULL,
    retrieved_at timestamp(6) without time zone NOT NULL,
    source character varying(100)
);


--
-- Name: building_permit_details_permit_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.building_permit_details ALTER COLUMN permit_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.building_permit_details_permit_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: comparable_property_details; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.comparable_property_details (
    comparable_id bigint NOT NULL,
    age_years integer,
    amenity_score numeric(5,2),
    area_sqft integer,
    bhk character varying(10),
    city character varying(100) NOT NULL,
    external_listing_id character varying(100),
    floor integer,
    handoff_url character varying(500),
    locality character varying(100),
    price numeric(15,2),
    price_per_sqft numeric(10,2),
    property_id bigint NOT NULL,
    property_type character varying(50),
    rera_id character varying(50),
    retrieved_at timestamp(6) without time zone NOT NULL,
    source character varying(100),
    total_floors integer,
    verified boolean
);


--
-- Name: comparable_property_details_comparable_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.comparable_property_details ALTER COLUMN comparable_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.comparable_property_details_comparable_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: due_diligence_reports; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.due_diligence_reports (
    report_id bigint NOT NULL,
    executive_summary character varying(2000),
    generated_at timestamp(6) without time zone NOT NULL,
    generated_by bigint NOT NULL,
    property_id bigint NOT NULL,
    risk_assessment_id bigint,
    status character varying(30),
    updated_at timestamp(6) without time zone NOT NULL,
    aggregation_run_id bigint
);


--
-- Name: due_diligence_reports_report_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.due_diligence_reports ALTER COLUMN report_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.due_diligence_reports_report_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: environmental_details; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.environmental_details (
    environmental_id bigint NOT NULL,
    description character varying(500),
    external_record_id character varying(100),
    property_id bigint NOT NULL,
    record_type character varying(50),
    retrieved_at timestamp(6) without time zone NOT NULL,
    risk_level character varying(30),
    source character varying(100),
    status character varying(30)
);


--
-- Name: environmental_details_environmental_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.environmental_details ALTER COLUMN environmental_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.environmental_details_environmental_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: flood_zone_details; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.flood_zone_details (
    flood_zone_id bigint NOT NULL,
    effective_date date,
    property_id bigint NOT NULL,
    retrieved_at timestamp(6) without time zone NOT NULL,
    risk_level character varying(30),
    source character varying(100),
    zone character varying(20)
);


--
-- Name: flood_zone_details_flood_zone_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.flood_zone_details ALTER COLUMN flood_zone_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.flood_zone_details_flood_zone_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: market_trends; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.market_trends (
    market_trend_id bigint NOT NULL,
    aggregation_run_id bigint,
    avg_price_per_sqft numeric(15,2),
    city character varying(100) NOT NULL,
    demand_pulse numeric(5,2),
    investment_grade character varying(20),
    livability_grade character varying(20),
    locality character varying(100),
    period character varying(20) NOT NULL,
    property_id bigint,
    retrieved_at timestamp(6) without time zone NOT NULL,
    source character varying(50) NOT NULL,
    supply_count integer
);


--
-- Name: market_trends_market_trend_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.market_trends ALTER COLUMN market_trend_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.market_trends_market_trend_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: notifications; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.notifications (
    notification_id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    message character varying(500) NOT NULL,
    notification_type character varying(50) NOT NULL,
    property_id bigint,
    report_id bigint,
    sent_at timestamp(6) without time zone,
    status character varying(30),
    user_id bigint NOT NULL
);


--
-- Name: notifications_notification_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.notifications ALTER COLUMN notification_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.notifications_notification_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: ownership_details; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.ownership_details (
    ownership_id bigint NOT NULL,
    external_record_id character varying(100),
    owner_name character varying(100) NOT NULL,
    ownership_type character varying(50),
    property_id bigint NOT NULL,
    record_date date,
    source character varying(100)
);


--
-- Name: ownership_details_ownership_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.ownership_details ALTER COLUMN ownership_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.ownership_details_ownership_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: property_details; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.property_details (
    property_id bigint NOT NULL,
    address character varying(255) NOT NULL,
    address_complete boolean,
    age character varying(50),
    amenities character varying(4000),
    area_text character varying(100),
    availability character varying(50),
    balconies integer,
    bathrooms integer,
    bedrooms integer,
    brokerage numeric(15,2),
    carpet_area_sqft numeric(10,2),
    city character varying(100) NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    dealer character varying(150),
    deposit numeric(15,2),
    description oid,
    expiry_date character varying(50),
    external_listing_id character varying(100),
    facing character varying(50),
    floor character varying(20),
    furnishing character varying(50),
    gated_community boolean,
    geocode_granularity character varying(40),
    google_place_id character varying(150),
    google_response_id character varying(100),
    government_identifier character varying(150),
    has_unconfirmed_components boolean,
    images oid,
    latitude numeric(10,8),
    listed_by character varying(30),
    listing_url character varying(1000),
    locality character varying(150),
    longitude numeric(11,8),
    map_accuracy character varying(30),
    municipal_assessment_identifier character varying(150),
    original_currency character varying(10),
    original_price numeric(15,2),
    place_types character varying(255),
    plus_code character varying(30),
    possible_next_action character varying(100),
    postal_code character varying(20),
    posting_date character varying(50),
    price numeric(15,2),
    price_per_sqft numeric(10,2),
    property_subtype character varying(100),
    property_type character varying(50),
    rera_id character varying(100),
    source character varying(50),
    sqm numeric(10,2),
    state character varying(100) NOT NULL,
    super_area_sqft numeric(10,2),
    title character varying(500),
    total_floors integer,
    transaction character varying(30),
    update_date character varying(50),
    updated_at timestamp(6) without time zone NOT NULL,
    validation_granularity character varying(40),
    verified boolean,
    searched_by bigint
);


--
-- Name: property_details_property_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.property_details ALTER COLUMN property_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.property_details_property_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: property_history; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.property_history (
    history_id bigint NOT NULL,
    captured_at timestamp(6) without time zone NOT NULL,
    environmental_id bigint,
    flood_zone_id bigint,
    ownership_id bigint,
    permit_id bigint,
    property_id bigint NOT NULL,
    tax_id bigint,
    utility_id bigint,
    zoning_id bigint
);


--
-- Name: property_history_history_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.property_history ALTER COLUMN history_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.property_history_history_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: property_monitoring; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.property_monitoring (
    monitoring_id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    enabled boolean NOT NULL,
    last_checked_at timestamp(6) without time zone,
    next_check_at timestamp(6) without time zone,
    property_id bigint NOT NULL,
    user_id bigint NOT NULL
);


--
-- Name: property_monitoring_monitoring_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.property_monitoring ALTER COLUMN monitoring_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.property_monitoring_monitoring_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: provider_observations; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.provider_observations (
    observation_id bigint NOT NULL,
    aggregation_run_id bigint NOT NULL,
    error_message character varying(1000),
    external_record_id character varying(150),
    http_status integer,
    operation character varying(100) NOT NULL,
    property_id bigint NOT NULL,
    provider character varying(50) NOT NULL,
    response_payload oid,
    retrieved_at timestamp(6) without time zone NOT NULL,
    status character varying(30) NOT NULL
);


--
-- Name: provider_observations_observation_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.provider_observations ALTER COLUMN observation_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.provider_observations_observation_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: refresh_tokens; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.refresh_tokens (
    token_id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    expires_at timestamp(6) without time zone NOT NULL,
    replaced_by_token character varying(512),
    revoked boolean NOT NULL,
    token character varying(512) NOT NULL,
    user_id bigint NOT NULL
);


--
-- Name: refresh_tokens_token_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.refresh_tokens ALTER COLUMN token_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.refresh_tokens_token_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: risk_assessment_details; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.risk_assessment_details (
    risk_assessment_id bigint NOT NULL,
    assessed_at timestamp(6) without time zone NOT NULL,
    flood_risk numeric(5,2),
    legal_risk numeric(5,2),
    overall_score numeric(5,2),
    ownership_verification numeric(5,2),
    permit_compliance numeric(5,2),
    property_id bigint NOT NULL,
    tax_risk numeric(5,2),
    zoning_compliance numeric(5,2)
);


--
-- Name: risk_assessment_details_risk_assessment_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.risk_assessment_details ALTER COLUMN risk_assessment_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.risk_assessment_details_risk_assessment_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: roles; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.roles (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    description character varying(255),
    name character varying(50) NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL
);


--
-- Name: roles_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.roles ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.roles_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: supporting_docs; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.supporting_docs (
    document_id bigint NOT NULL,
    file_name character varying(255) NOT NULL,
    file_path character varying(500) NOT NULL,
    file_type character varying(50),
    property_id bigint NOT NULL,
    report_id bigint NOT NULL,
    uploaded_at timestamp(6) without time zone NOT NULL,
    uploaded_by bigint NOT NULL
);


--
-- Name: supporting_docs_document_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.supporting_docs ALTER COLUMN document_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.supporting_docs_document_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tax_details; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tax_details (
    tax_id bigint NOT NULL,
    external_record_id character varying(100),
    payment_status character varying(30),
    property_id bigint NOT NULL,
    retrieved_at timestamp(6) without time zone NOT NULL,
    source character varying(100),
    tax_amount numeric(15,2),
    tax_due numeric(15,2),
    tax_pay_date date
);


--
-- Name: tax_details_tax_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.tax_details ALTER COLUMN tax_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tax_details_tax_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: user_profiles; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.user_profiles (
    profile_id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    first_name character varying(50) NOT NULL,
    job_title character varying(100),
    last_name character varying(50) NOT NULL,
    organization character varying(150),
    phone character varying(20),
    profile_picture character varying(500),
    timezone character varying(50),
    updated_at timestamp(6) without time zone NOT NULL,
    user_id bigint NOT NULL
);


--
-- Name: user_profiles_profile_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.user_profiles ALTER COLUMN profile_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.user_profiles_profile_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.users (
    user_id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    email character varying(100) NOT NULL,
    is_active boolean NOT NULL,
    password_hash character varying(255) NOT NULL,
    role_id bigint NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL
);


--
-- Name: users_user_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.users ALTER COLUMN user_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: utility_details; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.utility_details (
    utility_id bigint NOT NULL,
    availability_status character varying(30),
    property_id bigint NOT NULL,
    provider character varying(100),
    retrieved_at timestamp(6) without time zone NOT NULL,
    source character varying(100),
    utility_type character varying(50)
);


--
-- Name: utility_details_utility_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.utility_details ALTER COLUMN utility_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.utility_details_utility_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: zoning_details; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.zoning_details (
    zoning_id bigint NOT NULL,
    allowed_use character varying(200),
    effective_from date,
    effective_to date,
    property_id bigint NOT NULL,
    retrieved_at timestamp(6) without time zone NOT NULL,
    source character varying(100),
    zoning_code character varying(30) NOT NULL,
    zoning_status character varying(30)
);


--
-- Name: zoning_details_zoning_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.zoning_details ALTER COLUMN zoning_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.zoning_details_zoning_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: activity_logs activity_logs_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.activity_logs
    ADD CONSTRAINT activity_logs_pkey PRIMARY KEY (activity_log_id);


--
-- Name: aggregation_runs aggregation_runs_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.aggregation_runs
    ADD CONSTRAINT aggregation_runs_pkey PRIMARY KEY (aggregation_run_id);


--
-- Name: api_logs api_logs_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.api_logs
    ADD CONSTRAINT api_logs_pkey PRIMARY KEY (api_log_id);


--
-- Name: building_permit_details building_permit_details_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.building_permit_details
    ADD CONSTRAINT building_permit_details_pkey PRIMARY KEY (permit_id);


--
-- Name: comparable_property_details comparable_property_details_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.comparable_property_details
    ADD CONSTRAINT comparable_property_details_pkey PRIMARY KEY (comparable_id);


--
-- Name: due_diligence_reports due_diligence_reports_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.due_diligence_reports
    ADD CONSTRAINT due_diligence_reports_pkey PRIMARY KEY (report_id);


--
-- Name: environmental_details environmental_details_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.environmental_details
    ADD CONSTRAINT environmental_details_pkey PRIMARY KEY (environmental_id);


--
-- Name: flood_zone_details flood_zone_details_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.flood_zone_details
    ADD CONSTRAINT flood_zone_details_pkey PRIMARY KEY (flood_zone_id);


--
-- Name: market_trends market_trends_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.market_trends
    ADD CONSTRAINT market_trends_pkey PRIMARY KEY (market_trend_id);


--
-- Name: notifications notifications_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.notifications
    ADD CONSTRAINT notifications_pkey PRIMARY KEY (notification_id);


--
-- Name: ownership_details ownership_details_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ownership_details
    ADD CONSTRAINT ownership_details_pkey PRIMARY KEY (ownership_id);


--
-- Name: property_details property_details_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.property_details
    ADD CONSTRAINT property_details_pkey PRIMARY KEY (property_id);


--
-- Name: property_history property_history_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.property_history
    ADD CONSTRAINT property_history_pkey PRIMARY KEY (history_id);


--
-- Name: property_monitoring property_monitoring_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.property_monitoring
    ADD CONSTRAINT property_monitoring_pkey PRIMARY KEY (monitoring_id);


--
-- Name: provider_observations provider_observations_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.provider_observations
    ADD CONSTRAINT provider_observations_pkey PRIMARY KEY (observation_id);


--
-- Name: refresh_tokens refresh_tokens_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.refresh_tokens
    ADD CONSTRAINT refresh_tokens_pkey PRIMARY KEY (token_id);


--
-- Name: risk_assessment_details risk_assessment_details_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.risk_assessment_details
    ADD CONSTRAINT risk_assessment_details_pkey PRIMARY KEY (risk_assessment_id);


--
-- Name: roles roles_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.roles
    ADD CONSTRAINT roles_pkey PRIMARY KEY (id);


--
-- Name: supporting_docs supporting_docs_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.supporting_docs
    ADD CONSTRAINT supporting_docs_pkey PRIMARY KEY (document_id);


--
-- Name: tax_details tax_details_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tax_details
    ADD CONSTRAINT tax_details_pkey PRIMARY KEY (tax_id);


--
-- Name: users uk6dotkott2kjsp8vw4d0m25fb7; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT uk6dotkott2kjsp8vw4d0m25fb7 UNIQUE (email);


--
-- Name: property_monitoring uk_property_monitoring_user_property; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.property_monitoring
    ADD CONSTRAINT uk_property_monitoring_user_property UNIQUE (user_id, property_id);


--
-- Name: user_profiles uk_user_profile_user_id; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_profiles
    ADD CONSTRAINT uk_user_profile_user_id UNIQUE (user_id);


--
-- Name: refresh_tokens ukghpmfn23vmxfu3spu3lfg4r2d; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.refresh_tokens
    ADD CONSTRAINT ukghpmfn23vmxfu3spu3lfg4r2d UNIQUE (token);


--
-- Name: roles ukofx66keruapi6vyqpv6f2or37; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.roles
    ADD CONSTRAINT ukofx66keruapi6vyqpv6f2or37 UNIQUE (name);


--
-- Name: user_profiles user_profiles_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_profiles
    ADD CONSTRAINT user_profiles_pkey PRIMARY KEY (profile_id);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (user_id);


--
-- Name: utility_details utility_details_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.utility_details
    ADD CONSTRAINT utility_details_pkey PRIMARY KEY (utility_id);


--
-- Name: zoning_details zoning_details_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.zoning_details
    ADD CONSTRAINT zoning_details_pkey PRIMARY KEY (zoning_id);


--
-- Name: flood_zone_details fk1a9g1if0h9vums667yamshalh; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.flood_zone_details
    ADD CONSTRAINT fk1a9g1if0h9vums667yamshalh FOREIGN KEY (property_id) REFERENCES public.property_details(property_id);


--
-- Name: property_history fk365skymto250rawj9kcndhfps; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.property_history
    ADD CONSTRAINT fk365skymto250rawj9kcndhfps FOREIGN KEY (zoning_id) REFERENCES public.zoning_details(zoning_id);


--
-- Name: aggregation_runs fk54r0lfrbn0to7c2kg02u50cic; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.aggregation_runs
    ADD CONSTRAINT fk54r0lfrbn0to7c2kg02u50cic FOREIGN KEY (property_id) REFERENCES public.property_details(property_id);


--
-- Name: activity_logs fk5bm1lt4f4eevt8lv2517soakd; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.activity_logs
    ADD CONSTRAINT fk5bm1lt4f4eevt8lv2517soakd FOREIGN KEY (user_id) REFERENCES public.users(user_id);


--
-- Name: property_history fk7ixrmkxp55vt8vkp05uvaku4h; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.property_history
    ADD CONSTRAINT fk7ixrmkxp55vt8vkp05uvaku4h FOREIGN KEY (utility_id) REFERENCES public.utility_details(utility_id);


--
-- Name: building_permit_details fk7jpcv7lhsounl3qwrjotevoc7; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.building_permit_details
    ADD CONSTRAINT fk7jpcv7lhsounl3qwrjotevoc7 FOREIGN KEY (property_id) REFERENCES public.property_details(property_id);


--
-- Name: notifications fk8564vj1ykxn2l4tmu1vx9l98p; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.notifications
    ADD CONSTRAINT fk8564vj1ykxn2l4tmu1vx9l98p FOREIGN KEY (property_id) REFERENCES public.property_details(property_id);


--
-- Name: supporting_docs fk8lqowetgehgu2hypw0lv5qfii; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.supporting_docs
    ADD CONSTRAINT fk8lqowetgehgu2hypw0lv5qfii FOREIGN KEY (property_id) REFERENCES public.property_details(property_id);


--
-- Name: notifications fk8wvsvdqvdkcc1o69sy1o3wamn; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.notifications
    ADD CONSTRAINT fk8wvsvdqvdkcc1o69sy1o3wamn FOREIGN KEY (report_id) REFERENCES public.due_diligence_reports(report_id);


--
-- Name: property_history fk9qe5gdionnhh3mbmpipxxfgn3; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.property_history
    ADD CONSTRAINT fk9qe5gdionnhh3mbmpipxxfgn3 FOREIGN KEY (property_id) REFERENCES public.property_details(property_id);


--
-- Name: notifications fk9y21adhxn0ayjhfocscqox7bh; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.notifications
    ADD CONSTRAINT fk9y21adhxn0ayjhfocscqox7bh FOREIGN KEY (user_id) REFERENCES public.users(user_id);


--
-- Name: tax_details fkbpmux4xny18vjk4bagtxoioh5; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tax_details
    ADD CONSTRAINT fkbpmux4xny18vjk4bagtxoioh5 FOREIGN KEY (property_id) REFERENCES public.property_details(property_id);


--
-- Name: environmental_details fkclvti85sqvipvim3fqfc5okei; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.environmental_details
    ADD CONSTRAINT fkclvti85sqvipvim3fqfc5okei FOREIGN KEY (property_id) REFERENCES public.property_details(property_id);


--
-- Name: property_history fkdmc4jyypfwwt47pmbhv850j7i; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.property_history
    ADD CONSTRAINT fkdmc4jyypfwwt47pmbhv850j7i FOREIGN KEY (environmental_id) REFERENCES public.environmental_details(environmental_id);


--
-- Name: supporting_docs fkdwveawt31ntph00gqh7oij4kg; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.supporting_docs
    ADD CONSTRAINT fkdwveawt31ntph00gqh7oij4kg FOREIGN KEY (report_id) REFERENCES public.due_diligence_reports(report_id);


--
-- Name: comparable_property_details fke2sal9p2lu8cbsvl4pqlv5699; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.comparable_property_details
    ADD CONSTRAINT fke2sal9p2lu8cbsvl4pqlv5699 FOREIGN KEY (property_id) REFERENCES public.property_details(property_id);


--
-- Name: property_history fkftlilm4y9oa4cggo93mss3926; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.property_history
    ADD CONSTRAINT fkftlilm4y9oa4cggo93mss3926 FOREIGN KEY (permit_id) REFERENCES public.building_permit_details(permit_id);


--
-- Name: property_monitoring fkgmty4q1ga4sth26yph4ucawit; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.property_monitoring
    ADD CONSTRAINT fkgmty4q1ga4sth26yph4ucawit FOREIGN KEY (property_id) REFERENCES public.property_details(property_id);


--
-- Name: ownership_details fkhu4r4sjw02gn2yog9qyiln9d0; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ownership_details
    ADD CONSTRAINT fkhu4r4sjw02gn2yog9qyiln9d0 FOREIGN KEY (property_id) REFERENCES public.property_details(property_id);


--
-- Name: provider_observations fkiw0q0fmioqbrw4hoi9pf0254d; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.provider_observations
    ADD CONSTRAINT fkiw0q0fmioqbrw4hoi9pf0254d FOREIGN KEY (aggregation_run_id) REFERENCES public.aggregation_runs(aggregation_run_id);


--
-- Name: user_profiles fkjcad5nfve11khsnpwj1mv8frj; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_profiles
    ADD CONSTRAINT fkjcad5nfve11khsnpwj1mv8frj FOREIGN KEY (user_id) REFERENCES public.users(user_id);


--
-- Name: supporting_docs fkkn9rrik34lhxaykgm07qukq4n; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.supporting_docs
    ADD CONSTRAINT fkkn9rrik34lhxaykgm07qukq4n FOREIGN KEY (uploaded_by) REFERENCES public.users(user_id);


--
-- Name: property_history fkl030d8bmdplu2jlia0leoqehd; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.property_history
    ADD CONSTRAINT fkl030d8bmdplu2jlia0leoqehd FOREIGN KEY (ownership_id) REFERENCES public.ownership_details(ownership_id);


--
-- Name: property_details fklw22xpeyw0sf11ovtdfa10t5c; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.property_details
    ADD CONSTRAINT fklw22xpeyw0sf11ovtdfa10t5c FOREIGN KEY (searched_by) REFERENCES public.users(user_id);


--
-- Name: due_diligence_reports fkm6wo19uvnwed5xlhm3eyaaaad; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.due_diligence_reports
    ADD CONSTRAINT fkm6wo19uvnwed5xlhm3eyaaaad FOREIGN KEY (risk_assessment_id) REFERENCES public.risk_assessment_details(risk_assessment_id);


--
-- Name: due_diligence_reports fkn7mltnnux08oa99lx2ofad94m; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.due_diligence_reports
    ADD CONSTRAINT fkn7mltnnux08oa99lx2ofad94m FOREIGN KEY (aggregation_run_id) REFERENCES public.aggregation_runs(aggregation_run_id);


--
-- Name: risk_assessment_details fko7b1on5vtf5esuch6pqxxqwvs; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.risk_assessment_details
    ADD CONSTRAINT fko7b1on5vtf5esuch6pqxxqwvs FOREIGN KEY (property_id) REFERENCES public.property_details(property_id);


--
-- Name: utility_details fkof1g7yelb0vgcwj7wkaksvljk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.utility_details
    ADD CONSTRAINT fkof1g7yelb0vgcwj7wkaksvljk FOREIGN KEY (property_id) REFERENCES public.property_details(property_id);


--
-- Name: property_monitoring fkottkj16sq1vdq4l4yooixkvx; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.property_monitoring
    ADD CONSTRAINT fkottkj16sq1vdq4l4yooixkvx FOREIGN KEY (user_id) REFERENCES public.users(user_id);


--
-- Name: users fkp56c1712k691lhsyewcssf40f; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT fkp56c1712k691lhsyewcssf40f FOREIGN KEY (role_id) REFERENCES public.roles(id);


--
-- Name: property_history fkpswxt6okdc11yxj92f8m8vwvo; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.property_history
    ADD CONSTRAINT fkpswxt6okdc11yxj92f8m8vwvo FOREIGN KEY (tax_id) REFERENCES public.tax_details(tax_id);


--
-- Name: property_history fkqmg14c6ia9pkljifit84bwb9y; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.property_history
    ADD CONSTRAINT fkqmg14c6ia9pkljifit84bwb9y FOREIGN KEY (flood_zone_id) REFERENCES public.flood_zone_details(flood_zone_id);


--
-- Name: due_diligence_reports fkqw71aqv99d7iichu3ivflw6n2; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.due_diligence_reports
    ADD CONSTRAINT fkqw71aqv99d7iichu3ivflw6n2 FOREIGN KEY (generated_by) REFERENCES public.users(user_id);


--
-- Name: zoning_details fkrmbaia49ypualwfpbrgpamvs4; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.zoning_details
    ADD CONSTRAINT fkrmbaia49ypualwfpbrgpamvs4 FOREIGN KEY (property_id) REFERENCES public.property_details(property_id);


--
-- Name: due_diligence_reports fksvap6dlw5wrv9myyajs3a2as3; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.due_diligence_reports
    ADD CONSTRAINT fksvap6dlw5wrv9myyajs3a2as3 FOREIGN KEY (property_id) REFERENCES public.property_details(property_id);


--
-- PostgreSQL database dump complete
--


