-- Saved properties (SRS): one saved row per (user, property) pair.
-- Mirrors the V1 table style exactly: bare CREATE TABLE, then identity
-- sequence, then ALTER TABLE ONLY constraints. V1 is never edited; the
-- 50-property seed is unaffected (saved_properties starts empty).

--
-- Name: saved_properties; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.saved_properties (
    saved_property_id bigint NOT NULL,
    user_id bigint NOT NULL,
    property_id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL
);


--
-- Name: saved_properties_saved_property_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.saved_properties ALTER COLUMN saved_property_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.saved_properties_saved_property_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: saved_properties saved_properties_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.saved_properties
    ADD CONSTRAINT saved_properties_pkey PRIMARY KEY (saved_property_id);


--
-- Name: saved_properties uk_saved_properties_user_property; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.saved_properties
    ADD CONSTRAINT uk_saved_properties_user_property UNIQUE (user_id, property_id);


--
-- Name: saved_properties fk_saved_properties_user; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.saved_properties
    ADD CONSTRAINT fk_saved_properties_user FOREIGN KEY (user_id) REFERENCES public.users(user_id);


--
-- Name: saved_properties fk_saved_properties_property; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.saved_properties
    ADD CONSTRAINT fk_saved_properties_property FOREIGN KEY (property_id) REFERENCES public.property_details(property_id);
