package com.realestate.duediligence.entity;

import jakarta.persistence.*;
import lombok.Data;

/**
 * Entity representing flood zone information for a property.
 *
 * WHY: Our SRS requires flood zone verification as part of the Due
 * Diligence module. This directly feeds into the Risk Assessment
 * module (Milestone 3), which is why riskLevel uses the same
 * LOW/MEDIUM/HIGH scale defined in our API contract.
 */
@Entity
@Table(name = "flood_zone_info")
@Data
public class FloodZoneInfo {

    // Primary key. Auto-generated by the database (auto-increment).
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /*
     * Links this flood zone record back to its property.
     * @JoinColumn creates the foreign key column "property_id".
     */
    @ManyToOne
    @JoinColumn(name = "property_id", nullable = false)
    private Property property;

    // The official flood zone designation (e.g. "Zone X", "Zone AE").
    // Kept as a String since real flood zone codes are standardized
    // externally (FEMA-style codes), not something we define ourselves.
    @Column(nullable = false)
    private String zone;

    // Risk level derived from the zone. Matches the same LOW/MEDIUM/HIGH
    // scale used in the overall Risk Assessment module (Milestone 3).
    @Enumerated(EnumType.STRING)
    @Column(nullable = false)
    private RiskLevel riskLevel;
}