package com.realestate.duediligence.entity;

import java.time.LocalDate;
import jakarta.persistence.*;
import lombok.Data;

/**
 * Entity representing one ownership record for a property.
 *
 * WHY: Our SRS requires tracking ownership history as part of the
 * Due Diligence module. A property can have multiple owners over time,
 * so this is a separate table, not extra columns on Property.
 */
@Entity
@Table(name = "ownership_records")
@Data
public class OwnershipRecord {

    // Primary key. Auto-generated by the database (auto-increment).
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /*
     * Many ownership records can belong to one property.
     * Example: Property A -> Owner 1, Owner 2, Owner 3
     * @JoinColumn creates the foreign key column "property_id".
     */
    @ManyToOne
    @JoinColumn(name = "property_id", nullable = false)
    private Property property;

    // Name of the person who owned the property during this period.
    @Column(nullable = false)
    private String ownerName;

    // The specific calendar date this owner acquired the property.
    // LocalDate is used because this is a real, specific date.
    @Column(nullable = false)
    private LocalDate acquiredDate;
}