package com.realestate.duediligence.entity;

import jakarta.persistence.*;
import lombok.Data;
import java.time.LocalDate;

/**
 * Entity representing one building permit record for a property.
 *
 * WHY: Our SRS requires tracking permit history as part of the Due Diligence
 * module. A property can have multiple permits over time (renovations,
 * additions, etc.), so this is a separate table.
 */
@Entity
@Table(name = "permit_records")
@Data
public class PermitRecord {

	// Primary key. Auto-generated by the database (auto-increment).
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private Long id;

	/*
	 * Links this permit record back to its property. Many permits can belong to one
	 * property over time.
	 * 
	 * @JoinColumn creates the foreign key column "property_id".
	 */
	@ManyToOne
	@JoinColumn(name = "property_id", nullable = false)
	private Property property;

	// The type of permit (e.g. "Renovation", "Electrical", "Addition").
	// Kept as a String since permit types vary widely and aren't a
	// small, fixed list.
	@Column(nullable = false)
	private String permitType;

	// The current status of this permit.
	@Enumerated(EnumType.STRING)
	@Column(nullable = false)
	private PermitStatus status;

	// The date this permit was officially issued.
	@Column(nullable = false)
	private LocalDate issuedDate;
}