package com.realestate.duediligence.entity;

import jakarta.persistence.*; 
import lombok.Data;
import java.math.BigDecimal;

/**
 * Entity representing one year's tax record for a property.
 *
 * WHY: Our SRS requires tracking tax history as part of the Due
 * Diligence module. A property has one tax record per year, so this
 * is a separate table, not extra columns on Property.
 */
@Entity
@Table(name = "tax_history")
@Data
public class TaxHistory {

    // Primary key. Auto-generated by the database (auto-increment).
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /*
     * Many tax history records can belong to one property.
     * Example: Property A -> 2023 record, 2024 record, 2025 record
     * @JoinColumn creates the foreign key column "property_id".
     */
    @ManyToOne
    @JoinColumn(name = "property_id", nullable = false)
    private Property property;

    // The tax year this record covers (e.g. 2025). A whole year,
    // not a specific date, so Integer is used rather than LocalDate.
    @Column(nullable = false)
    private Integer year;

    // The amount paid for this tax year. BigDecimal is used instead
    // of double/float to avoid rounding errors with money values.
    @Column(nullable = false)
    private BigDecimal amountPaid;

    // Whether this year's tax is paid, overdue, or partially paid.
    // Stored as text (e.g. "PAID") rather than a number, for readability.
    @Enumerated(EnumType.STRING)
    @Column(nullable = false)
    private TaxStatus status;
}