package com.realestate.duediligence.entity;

import jakarta.persistence.*;
import lombok.Data;

/**
 * Entity representing zoning information for a property.
 *
 * WHY: Our SRS requires zoning verification as part of the Due
 * Diligence module — confirming what a property is legally zoned
 * for, and whether its current use complies with that zoning.
 */
@Entity
@Table(name = "zoning_info")
@Data
public class ZoningInfo {

    // Primary key. Auto-generated by the database (auto-increment).
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /*
     * Links this zoning record back to its property.
     * @JoinColumn creates the foreign key column "property_id".
     */
    @ManyToOne
    @JoinColumn(name = "property_id", nullable = false)
    private Property property;

    // The zoning classification (e.g. "R1", "Commercial", "Agricultural").
    // Kept as a String since real-world zoning codes vary widely and
    // aren't a small, fixed list like our user roles.
    @Column(nullable = false)
    private String zoneType;

    // Whether the property's current use complies with its zoning.
    // A simple true/false is enough for this SRS requirement.
    @Column(nullable = false)
    private Boolean compliant;
}