package com.duedilligenceagent.backend.repositories;

import com.duedilligenceagent.backend.entities.DueDiligenceReport;
import org.springframework.data.jpa.repository.JpaRepository;

import java.util.List;
import java.util.Optional;

public interface DueDiligenceReportRepository extends JpaRepository<DueDiligenceReport, Long> {

    /** All reports generated for a property, newest first. */
    List<DueDiligenceReport> findByPropertyIdOrderByGeneratedAtDesc(Long propertyId);

    /** Latest report for a property (page reloads). */
    Optional<DueDiligenceReport> findFirstByPropertyIdOrderByGeneratedAtDesc(Long propertyId);

    /** All reports generated by a user, newest first (reports page). */
    List<DueDiligenceReport> findByGeneratedByOrderByGeneratedAtDesc(Long userId);
}
