spring.application.name=backend

#spring.datasource.url=jdbc:postgresql://localhost:5432/realestate_db
#spring.datasource.username=postgres
#spring.datasource.password=Anju@123

#db specific properties
spring.datasource.url=jdbc:mysql://${MYSQLHOST:localhost}:${MYSQLPORT:3306}/${MYSQLDATABASE:realstate_db}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=${MYSQLUSER:root}
spring.datasource.password=${MYSQLPASSWORD:ABHI1ranchi@}


#ORM s/w specific properties
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.format_sql=true

server.port=8081
