package com.duedilligenceagent.backend.service;

import com.duedilligenceagent.backend.dto.DiligenceDataResponse;
import com.duedilligenceagent.backend.dto.AggregationResponse;
import com.duedilligenceagent.backend.dto.ReportResponse;
import com.duedilligenceagent.backend.dto.RiskAssessmentResponse;
import com.duedilligenceagent.backend.entities.DueDiligenceReport;
import com.duedilligenceagent.backend.entities.Property;
import com.duedilligenceagent.backend.entities.RiskAssessmentDetails;
import com.duedilligenceagent.backend.exception.ResourceNotFoundException;
import com.duedilligenceagent.backend.repositories.AggregationRunRepository;
import com.duedilligenceagent.backend.repositories.DueDiligenceReportRepository;
import com.duedilligenceagent.backend.repositories.PropertyRepository;
import com.duedilligenceagent.backend.repositories.RiskAssessmentDetailsRepository;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.util.ArrayList;
import java.util.List;
import java.util.Locale;
import java.util.Objects;

/**
 * Generates due-diligence reports as a single pipeline: the stored-data
 * aggregation run inventories the property's diligence records first,
 * the risk engine calculates the assessment from those records, the
 * executive summary is built from the actual record statuses, and the
 * report row is persisted with the generating user and the linked run.
 * <p>
 * Reports are user-facing: the response carries the summary, the risk
 * scores, the record statuses and the data coverage — never provider
 * names, contract statuses or pipeline internals.
 */
@Service
@RequiredArgsConstructor
@Slf4j
public class ReportService {

    private final PropertyRepository propertyRepository;
    private final DueDiligenceReportRepository reportRepository;
    private final RiskAssessmentDetailsRepository riskAssessmentRepository;
    private final RiskAssessmentService riskAssessmentService;
    private final DiligenceService diligenceService;
    private final AggregationService aggregationService;
    private final AggregationRunRepository aggregationRunRepository;

    /** Single pipeline: aggregation inventory → risk → executive summary → persist. */
    @Transactional
    public ReportResponse generate(Long propertyId, Long generatedByUserId) {
        Property property = propertyRepository.findById(propertyId)
                .orElseThrow(() ->
                        new ResourceNotFoundException("Property not found with id: " + propertyId));

        AggregationResponse aggregation = aggregationService.aggregate(propertyId, null);
        RiskAssessmentDetails assessment = riskAssessmentService.calculateAndPersist(property);
        DiligenceDataResponse diligence = diligenceService.getDiligenceData(propertyId);

        String summary = buildExecutiveSummary(property, assessment, diligence);

        DueDiligenceReport report = reportRepository.save(DueDiligenceReport.builder()
                .propertyId(propertyId)
                .generatedBy(generatedByUserId)
                .riskAssessmentId(assessment.getRiskAssessmentId())
                .aggregationRunId(aggregation.getAggregationRunId())
                .executiveSummary(summary)
                .status("COMPLETED")
                .build());

        log.info("Generated due-diligence report id={} for property id={} by user id={} from aggregation run id={}",
                report.getReportId(), propertyId, generatedByUserId, aggregation.getAggregationRunId());

        return toResponse(report, property, assessment, diligence);
    }

    /** Latest stored report for a property, or empty when none was generated. */
    @Transactional(readOnly = true)
    public ReportResponse latest(Long propertyId) {
        propertyRepository.findById(propertyId)
                .orElseThrow(() ->
                        new ResourceNotFoundException("Property not found with id: " + propertyId));

        return reportRepository.findFirstByPropertyIdOrderByGeneratedAtDesc(propertyId)
                .map(this::toResponseWithLinkedData)
                .orElse(null);
    }

    /** All reports generated by a user, newest first (reports page). */
    @Transactional(readOnly = true)
    public List<ReportResponse> listForUser(Long userId) {
        return reportRepository.findByGeneratedByOrderByGeneratedAtDesc(userId).stream()
                .map(this::toResponseWithLinkedData)
                .filter(Objects::nonNull)
                .toList();
    }

    private ReportResponse toResponseWithLinkedData(DueDiligenceReport report) {
        Property property = propertyRepository.findById(report.getPropertyId()).orElse(null);
        if (property == null) {
            return null;
        }
        RiskAssessmentDetails assessment = report.getRiskAssessmentId() == null ? null
                : riskAssessmentRepository.findById(report.getRiskAssessmentId()).orElse(null);
        DiligenceDataResponse diligence = diligenceService.getDiligenceData(report.getPropertyId());
        return toResponse(report, property, assessment, diligence);
    }

    private ReportResponse toResponse(DueDiligenceReport report, Property property,
                                      RiskAssessmentDetails assessment, DiligenceDataResponse diligence) {
        String aggregationStatus = report.getAggregationRunId() == null ? null
                : aggregationRunRepository.findById(report.getAggregationRunId())
                        .map(run -> run.getStatus())
                        .orElse(null);
        return ReportResponse.builder()
                .reportId(report.getReportId())
                .propertyId(report.getPropertyId())
                .propertyAddress(property.getAddress())
                .riskTier(assessment == null ? "UNKNOWN" : RiskAssessmentService.tierOf(assessment.getOverallScore()))
                .executiveSummary(report.getExecutiveSummary())
                .status(report.getStatus())
                .generatedAt(report.getGeneratedAt())
                .aggregationRunId(report.getAggregationRunId())
                .aggregationStatus(aggregationStatus)
                .risk(toRiskResponse(assessment))
                .records(toRecordStatuses(diligence))
                .coverage(toCoverage(diligence))
                .build();
    }

    private RiskAssessmentResponse toRiskResponse(RiskAssessmentDetails assessment) {
        if (assessment == null) {
            return null;
        }
        return RiskAssessmentResponse.builder()
                .riskAssessmentId(assessment.getRiskAssessmentId())
                .propertyId(assessment.getPropertyId())
                .taxRisk(assessment.getTaxRisk())
                .legalRisk(assessment.getLegalRisk())
                .floodRisk(assessment.getFloodRisk())
                .permitCompliance(assessment.getPermitCompliance())
                .zoningCompliance(assessment.getZoningCompliance())
                .ownershipVerification(assessment.getOwnershipVerification())
                .overallScore(assessment.getOverallScore())
                .assessedAt(assessment.getAssessedAt())
                .build();
    }

    private ReportResponse.RecordStatuses toRecordStatuses(DiligenceDataResponse diligence) {
        return ReportResponse.RecordStatuses.builder()
                .taxStatus(diligence.getTax() == null ? null : diligence.getTax().getPaymentStatus())
                .permitStatus(diligence.getPermits() == null || diligence.getPermits().isEmpty()
                        ? null : diligence.getPermits().get(0).getPermitStatus())
                .zoningStatus(diligence.getZoning() == null ? null : diligence.getZoning().getZoningStatus())
                .floodRiskLevel(diligence.getFlood() == null ? null : diligence.getFlood().getRiskLevel())
                .environmentalStatus(diligence.getEnvironmental() == null
                        ? null : diligence.getEnvironmental().getStatus())
                .ownershipType(diligence.getOwnership() == null
                        ? null : diligence.getOwnership().getOwnershipType())
                .utilitiesAvailable(diligence.getUtilities() == null ? 0 : (int) diligence.getUtilities().stream()
                        .filter(u -> "AVAILABLE".equalsIgnoreCase(nullSafe(u.getAvailabilityStatus())))
                        .count())
                .build();
    }

    private ReportResponse.DataCoverage toCoverage(DiligenceDataResponse diligence) {
        List<String> missing = new ArrayList<>();
        if (diligence.getOwnership() == null) missing.add("ownership");
        if (diligence.getTax() == null) missing.add("property tax");
        if (diligence.getPermits() == null || diligence.getPermits().isEmpty()) missing.add("building permits");
        if (diligence.getZoning() == null) missing.add("zoning");
        if (diligence.getFlood() == null) missing.add("flood zone");
        if (diligence.getEnvironmental() == null) missing.add("environmental");
        if (diligence.getUtilities() == null || diligence.getUtilities().isEmpty()) missing.add("utilities");
        if (diligence.getComparables() == null || diligence.getComparables().isEmpty()) missing.add("comparable listings");
        if (diligence.getMarketTrends() == null || diligence.getMarketTrends().isEmpty()) missing.add("market trends");

        return ReportResponse.DataCoverage.builder()
                .ownershipRecord(diligence.getOwnership() != null)
                .taxRecord(diligence.getTax() != null)
                .permitRecord(diligence.getPermits() != null && !diligence.getPermits().isEmpty())
                .zoningRecord(diligence.getZoning() != null)
                .floodRecord(diligence.getFlood() != null)
                .environmentalRecord(diligence.getEnvironmental() != null)
                .utilityRecords(diligence.getUtilities() != null && !diligence.getUtilities().isEmpty())
                .comparablesCount(diligence.getComparables() == null ? 0 : diligence.getComparables().size())
                .marketTrendsCount(diligence.getMarketTrends() == null ? 0 : diligence.getMarketTrends().size())
                .missingSections(missing)
                .build();
    }

    /**
     * Builds the executive summary from the actual record statuses in a
     * professional analyst voice: an overall-risk opening sentence,
     * full-clause concerns (domains scoring ≥ 45) or a clean-bill sentence,
     * the ownership position, market context when trends are stored, and a
     * data-completeness closing line.
     */
    private String buildExecutiveSummary(Property property, RiskAssessmentDetails assessment,
                                        DiligenceDataResponse diligence) {
        ReportResponse.DataCoverage coverage = toCoverage(diligence);

        // Insufficient data: no diligence records exist — no fabricated scores.
        if (assessment.getOverallScore() == null) {
            return "No due-diligence records are available for this property yet, so a "
                    + "risk assessment could not be performed. The following sections remain "
                    + "unsourced and must be populated before the property can be evaluated: "
                    + String.join(", ", coverage.getMissingSections()) + ".";
        }

        String tier = RiskAssessmentService.tierOf(assessment.getOverallScore());
        String tierPhrase = switch (tier) {
            case "LOW" -> "a low overall risk profile";
            case "MODERATE" -> "a moderate overall risk profile";
            case "ELEVATED" -> "an elevated overall risk profile";
            case "HIGH" -> "a high overall risk profile";
            default -> "an unclassified overall risk profile";
        };
        StringBuilder sb = new StringBuilder("This property presents ")
                .append(tierPhrase)
                .append(" (")
                .append(assessment.getOverallScore().stripTrailingZeros().toPlainString())
                .append("/100). ");

        List<String> concerns = concerns(assessment, diligence);
        if (concerns.isEmpty()) {
            sb.append("No material concerns were identified in the available diligence records. ");
        } else if (concerns.size() == 1) {
            sb.append("The assessment identified one material concern. ")
                    .append(concerns.get(0)).append(". ");
        } else {
            sb.append("The assessment identified material concerns. ")
                    .append(String.join(". ", concerns)).append(". ");
        }

        if (diligence.getOwnership() != null) {
            sb.append("Ownership is recorded as ")
                    .append(humanize(diligence.getOwnership().getOwnershipType()))
                    .append(". ");
        }

        String market = marketContext(diligence);
        if (market != null) {
            sb.append(market).append(' ');
        }

        sb.append(completenessLine(coverage));
        return sb.toString().trim();
    }

    private List<String> concerns(RiskAssessmentDetails assessment, DiligenceDataResponse diligence) {
        List<String> concerns = new ArrayList<>();
        if (score(assessment.getTaxRisk()) >= 45) {
            String status = diligence.getTax() == null ? null : diligence.getTax().getPaymentStatus();
            concerns.add(status == null
                    ? "Property tax compliance could not be verified because no record is on file"
                    : "Property tax payments are " + lowerHuman(statusOf(status, "pending")));
        }
        if (score(assessment.getFloodRisk()) >= 45) {
            String level = diligence.getFlood() == null ? null : diligence.getFlood().getRiskLevel();
            concerns.add(level == null
                    ? "Flood-zone exposure could not be verified because no record is on file"
                    : "The property lies in a " + lowerHuman(level) + "-risk flood zone");
        }
        if (score(assessment.getPermitCompliance()) >= 45) {
            String permitStatus = diligence.getPermits() == null || diligence.getPermits().isEmpty()
                    ? null : diligence.getPermits().get(0).getPermitStatus();
            concerns.add(permitStatus == null
                    ? "Building permits could not be verified because no record is on file"
                    : "On building permits, " + permitPhrase(permitStatus));
        }
        if (score(assessment.getZoningCompliance()) >= 45) {
            String status = diligence.getZoning() == null ? null : diligence.getZoning().getZoningStatus();
            concerns.add(status == null
                    ? "Zoning compliance could not be verified because no record is on file"
                    : "Zoning compliance is " + lowerHuman(statusOf(status, "pending")));
        }
        if (score(assessment.getLegalRisk()) >= 45) {
            String status = diligence.getEnvironmental() == null ? null : diligence.getEnvironmental().getStatus();
            concerns.add(status == null
                    ? "Environmental clearance could not be verified because no record is on file"
                    : "The environmental review is " + lowerHuman(status));
        }
        if (score(assessment.getOwnershipVerification()) >= 45) {
            concerns.add("The ownership record could not be verified");
        }
        return concerns;
    }

    /** One-line data-completeness note derived from the coverage counts. */
    private String completenessLine(ReportResponse.DataCoverage coverage) {
        int have = 0;
        if (coverage.isOwnershipRecord()) have++;
        if (coverage.isTaxRecord()) have++;
        if (coverage.isPermitRecord()) have++;
        if (coverage.isZoningRecord()) have++;
        if (coverage.isFloodRecord()) have++;
        if (coverage.isEnvironmentalRecord()) have++;
        if (coverage.isUtilityRecords()) have++;
        int comparables = coverage.getComparablesCount() == null ? 0 : coverage.getComparablesCount();
        int trends = coverage.getMarketTrendsCount() == null ? 0 : coverage.getMarketTrendsCount();

        String base = "This assessment draws on " + have + " of 8 diligence record types"
                + (comparables > 0 ? " and " + comparables + " comparable listings" : "") + ".";
        if (coverage.getMissingSections() == null || coverage.getMissingSections().isEmpty()) {
            return base.replace(".", " Complete coverage across all sections.");
        }
        return base + " Unavailable sections: "
                + String.join(", ", coverage.getMissingSections()) + ".";
    }

    /** Permit phrasing that reads correctly in a sentence. */
    private static String permitPhrase(String status) {
        return switch (statusOf(status, "PENDING").toUpperCase(Locale.ROOT)) {
            case "APPROVED" -> "the latest permit is approved";
            case "COMPLETED" -> "permitted works are completed";
            case "PENDING" -> "the latest permit remains pending approval";
            case "EXPIRED" -> "the latest permit has expired";
            default -> "the latest permit status is " + lowerHuman(status);
        };
    }

    private String marketContext(DiligenceDataResponse diligence) {
        if (diligence.getMarketTrends() == null || diligence.getMarketTrends().isEmpty()) {
            return null;
        }
        DiligenceDataResponse.MarketTrendRecord latest = diligence.getMarketTrends().get(0);
        String locality = latest.getLocality() != null ? latest.getLocality() : "the city";
        return "Comparable market data indicates an average asking price of ₹"
                + latest.getAvgPricePerSqft().stripTrailingZeros().toPlainString()
                + "/sqft in " + locality + " for " + latest.getPeriod() + ".";
    }

    private static double score(java.math.BigDecimal value) {
        return value == null ? 100 : value.doubleValue();
    }

    private static String statusOf(String value, String fallback) {
        return value == null || value.isBlank() ? fallback : value;
    }

    private static String humanize(String value) {
        if (value == null) {
            return "";
        }
        String lower = value.trim().toLowerCase(Locale.ROOT).replace('_', ' ');
        return Character.toUpperCase(lower.charAt(0)) + lower.substring(1);
    }

    private static String lowerHuman(String value) {
        return humanize(value).toLowerCase(Locale.ROOT);
    }

    private static String nullSafe(String value) {
        return value == null ? "" : value;
    }
}
