package com.duedilligenceagent.backend.service;

import com.duedilligenceagent.backend.dto.DiligenceDataResponse;
import com.duedilligenceagent.backend.dto.ReportResponse;
import com.duedilligenceagent.backend.dto.RiskAssessmentResponse;
import com.duedilligenceagent.backend.entities.DueDiligenceReport;
import com.duedilligenceagent.backend.entities.Property;
import com.duedilligenceagent.backend.entities.RiskAssessmentDetails;
import com.duedilligenceagent.backend.exception.ResourceNotFoundException;
import com.duedilligenceagent.backend.repositories.DueDiligenceReportRepository;
import com.duedilligenceagent.backend.repositories.PropertyRepository;
import com.duedilligenceagent.backend.repositories.RiskAssessmentDetailsRepository;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.util.ArrayList;
import java.util.List;
import java.util.Locale;
import java.util.Objects;

/**
 * Generates due-diligence reports from the property's stored data:
 * the risk engine calculates the assessment from the diligence records,
 * the executive summary is built from the actual record statuses, and the
 * report row is persisted with the generating user.
 * <p>
 * Reports are user-facing: the response carries the summary, the risk
 * scores, the record statuses and the data coverage — never provider
 * names, contract statuses or pipeline internals.
 */
@Service
@RequiredArgsConstructor
@Slf4j
public class ReportService {

    private final PropertyRepository propertyRepository;
    private final DueDiligenceReportRepository reportRepository;
    private final RiskAssessmentDetailsRepository riskAssessmentRepository;
    private final RiskAssessmentService riskAssessmentService;
    private final DiligenceService diligenceService;

    /** Generates a fresh report: calculate risk → build summary → persist. */
    @Transactional
    public ReportResponse generate(Long propertyId, Long generatedByUserId) {
        Property property = propertyRepository.findById(propertyId)
                .orElseThrow(() ->
                        new ResourceNotFoundException("Property not found with id: " + propertyId));

        RiskAssessmentDetails assessment = riskAssessmentService.calculateAndPersist(property);
        DiligenceDataResponse diligence = diligenceService.getDiligenceData(propertyId);

        String summary = buildExecutiveSummary(property, assessment, diligence);

        DueDiligenceReport report = reportRepository.save(DueDiligenceReport.builder()
                .propertyId(propertyId)
                .generatedBy(generatedByUserId)
                .riskAssessmentId(assessment.getRiskAssessmentId())
                .executiveSummary(summary)
                .status("COMPLETED")
                .build());

        log.info("Generated due-diligence report id={} for property id={} by user id={}",
                report.getReportId(), propertyId, generatedByUserId);

        return toResponse(report, property, assessment, diligence);
    }

    /** Latest stored report for a property, or empty when none was generated. */
    @Transactional(readOnly = true)
    public ReportResponse latest(Long propertyId) {
        propertyRepository.findById(propertyId)
                .orElseThrow(() ->
                        new ResourceNotFoundException("Property not found with id: " + propertyId));

        return reportRepository.findFirstByPropertyIdOrderByGeneratedAtDesc(propertyId)
                .map(this::toResponseWithLinkedData)
                .orElse(null);
    }

    /** All reports generated by a user, newest first (reports page). */
    @Transactional(readOnly = true)
    public List<ReportResponse> listForUser(Long userId) {
        return reportRepository.findByGeneratedByOrderByGeneratedAtDesc(userId).stream()
                .map(this::toResponseWithLinkedData)
                .filter(Objects::nonNull)
                .toList();
    }

    private ReportResponse toResponseWithLinkedData(DueDiligenceReport report) {
        Property property = propertyRepository.findById(report.getPropertyId()).orElse(null);
        if (property == null) {
            return null;
        }
        RiskAssessmentDetails assessment = report.getRiskAssessmentId() == null ? null
                : riskAssessmentRepository.findById(report.getRiskAssessmentId()).orElse(null);
        DiligenceDataResponse diligence = diligenceService.getDiligenceData(report.getPropertyId());
        return toResponse(report, property, assessment, diligence);
    }

    private ReportResponse toResponse(DueDiligenceReport report, Property property,
                                      RiskAssessmentDetails assessment, DiligenceDataResponse diligence) {
        return ReportResponse.builder()
                .reportId(report.getReportId())
                .propertyId(report.getPropertyId())
                .propertyAddress(property.getAddress())
                .riskTier(assessment == null ? "UNKNOWN" : RiskAssessmentService.tierOf(assessment.getOverallScore()))
                .executiveSummary(report.getExecutiveSummary())
                .status(report.getStatus())
                .generatedAt(report.getGeneratedAt())
                .risk(toRiskResponse(assessment))
                .records(toRecordStatuses(diligence))
                .coverage(toCoverage(diligence))
                .build();
    }

    private RiskAssessmentResponse toRiskResponse(RiskAssessmentDetails assessment) {
        if (assessment == null) {
            return null;
        }
        return RiskAssessmentResponse.builder()
                .riskAssessmentId(assessment.getRiskAssessmentId())
                .propertyId(assessment.getPropertyId())
                .taxRisk(assessment.getTaxRisk())
                .legalRisk(assessment.getLegalRisk())
                .floodRisk(assessment.getFloodRisk())
                .permitCompliance(assessment.getPermitCompliance())
                .zoningCompliance(assessment.getZoningCompliance())
                .ownershipVerification(assessment.getOwnershipVerification())
                .overallScore(assessment.getOverallScore())
                .assessedAt(assessment.getAssessedAt())
                .build();
    }

    private ReportResponse.RecordStatuses toRecordStatuses(DiligenceDataResponse diligence) {
        return ReportResponse.RecordStatuses.builder()
                .taxStatus(diligence.getTax() == null ? null : diligence.getTax().getPaymentStatus())
                .permitStatus(diligence.getPermits() == null || diligence.getPermits().isEmpty()
                        ? null : diligence.getPermits().get(0).getPermitStatus())
                .zoningStatus(diligence.getZoning() == null ? null : diligence.getZoning().getZoningStatus())
                .floodRiskLevel(diligence.getFlood() == null ? null : diligence.getFlood().getRiskLevel())
                .environmentalStatus(diligence.getEnvironmental() == null
                        ? null : diligence.getEnvironmental().getStatus())
                .ownershipType(diligence.getOwnership() == null
                        ? null : diligence.getOwnership().getOwnershipType())
                .utilitiesAvailable(diligence.getUtilities() == null ? 0 : (int) diligence.getUtilities().stream()
                        .filter(u -> "AVAILABLE".equalsIgnoreCase(nullSafe(u.getAvailabilityStatus())))
                        .count())
                .build();
    }

    private ReportResponse.DataCoverage toCoverage(DiligenceDataResponse diligence) {
        List<String> missing = new ArrayList<>();
        if (diligence.getOwnership() == null) missing.add("ownership");
        if (diligence.getTax() == null) missing.add("property tax");
        if (diligence.getPermits() == null || diligence.getPermits().isEmpty()) missing.add("building permits");
        if (diligence.getZoning() == null) missing.add("zoning");
        if (diligence.getFlood() == null) missing.add("flood zone");
        if (diligence.getEnvironmental() == null) missing.add("environmental");
        if (diligence.getUtilities() == null || diligence.getUtilities().isEmpty()) missing.add("utilities");
        if (diligence.getComparables() == null || diligence.getComparables().isEmpty()) missing.add("comparable listings");
        if (diligence.getMarketTrends() == null || diligence.getMarketTrends().isEmpty()) missing.add("market trends");

        return ReportResponse.DataCoverage.builder()
                .ownershipRecord(diligence.getOwnership() != null)
                .taxRecord(diligence.getTax() != null)
                .permitRecord(diligence.getPermits() != null && !diligence.getPermits().isEmpty())
                .zoningRecord(diligence.getZoning() != null)
                .floodRecord(diligence.getFlood() != null)
                .environmentalRecord(diligence.getEnvironmental() != null)
                .utilityRecords(diligence.getUtilities() != null && !diligence.getUtilities().isEmpty())
                .comparablesCount(diligence.getComparables() == null ? 0 : diligence.getComparables().size())
                .marketTrendsCount(diligence.getMarketTrends() == null ? 0 : diligence.getMarketTrends().size())
                .missingSections(missing)
                .build();
    }

    /**
     * Builds the executive summary from the actual record statuses:
     * tier + overall score, the key concerns (domains scoring ≥ 45) or the
     * clean-bill phrases, and the market context when trends are stored.
     */
    private String buildExecutiveSummary(Property property, RiskAssessmentDetails assessment,
                                        DiligenceDataResponse diligence) {
        String tier = RiskAssessmentService.tierOf(assessment.getOverallScore());
        StringBuilder sb = new StringBuilder("Overall risk ")
                .append(tier)
                .append(" (")
                .append(assessment.getOverallScore().stripTrailingZeros().toPlainString())
                .append("/100). ");

        List<String> concerns = concerns(assessment, diligence);
        if (concerns.isEmpty()) {
            sb.append("No significant concerns identified in the stored records. ");
        } else {
            sb.append("Key concerns: ").append(String.join("; ", concerns)).append(". ");
        }

        if (diligence.getOwnership() != null) {
            sb.append("Ownership record present (")
                    .append(humanize(diligence.getOwnership().getOwnershipType()))
                    .append("). ");
        }

        String market = marketContext(diligence);
        if (market != null) {
            sb.append(market);
        }
        return sb.toString().trim();
    }

    private List<String> concerns(RiskAssessmentDetails assessment, DiligenceDataResponse diligence) {
        List<String> concerns = new ArrayList<>();
        if (score(assessment.getTaxRisk()) >= 45) {
            concerns.add("property tax " + humanize(statusOf(diligence.getTax() == null
                    ? null : diligence.getTax().getPaymentStatus(), "record missing")));
        }
        if (score(assessment.getFloodRisk()) >= 45) {
            concerns.add("flood risk " + humanize(statusOf(diligence.getFlood() == null
                    ? null : diligence.getFlood().getRiskLevel(), "record missing")));
        }
        if (score(assessment.getPermitCompliance()) >= 45) {
            String permitStatus = diligence.getPermits() == null || diligence.getPermits().isEmpty()
                    ? null : diligence.getPermits().get(0).getPermitStatus();
            concerns.add("building permit " + humanize(statusOf(permitStatus, "record missing")));
        }
        if (score(assessment.getZoningCompliance()) >= 45) {
            concerns.add("zoning " + humanize(statusOf(diligence.getZoning() == null
                    ? null : diligence.getZoning().getZoningStatus(), "record missing")));
        }
        if (score(assessment.getLegalRisk()) >= 45) {
            concerns.add("environmental review " + humanize(statusOf(diligence.getEnvironmental() == null
                    ? null : diligence.getEnvironmental().getStatus(), "record missing")));
        }
        if (score(assessment.getOwnershipVerification()) >= 45) {
            concerns.add("ownership record could not be verified");
        }
        return concerns;
    }

    private String marketContext(DiligenceDataResponse diligence) {
        if (diligence.getMarketTrends() == null || diligence.getMarketTrends().isEmpty()) {
            return null;
        }
        DiligenceDataResponse.MarketTrendRecord latest = diligence.getMarketTrends().get(0);
        String locality = latest.getLocality() != null ? latest.getLocality() : "the city";
        return "Market context: average price ₹"
                + latest.getAvgPricePerSqft().stripTrailingZeros().toPlainString()
                + "/sqft (" + locality + ", " + latest.getPeriod() + ").";
    }

    private static double score(java.math.BigDecimal value) {
        return value == null ? 100 : value.doubleValue();
    }

    private static String statusOf(String value, String fallback) {
        return value == null || value.isBlank() ? fallback : value;
    }

    private static String humanize(String value) {
        if (value == null) {
            return "";
        }
        String lower = value.trim().toLowerCase(Locale.ROOT).replace('_', ' ');
        return Character.toUpperCase(lower.charAt(0)) + lower.substring(1);
    }

    private static String nullSafe(String value) {
        return value == null ? "" : value;
    }
}
